export const data = [
  {
    title_default: 'Сказочное заморское яство',
    title_selected_hovered: 'Котэ не одобряет?',
    name: 'Нямушка',
    taste: 'с фуа-гра',
    portion: '10 порций',
    present: 'мышь в подарок',
    additional: '',
    weight: '0,5',
    units: 'кг',
    description_selected: 'Печень утки разварная с артишоками.',
  },
  {
    title_default: 'Сказочное заморское яство',
    title_selected_hovered: 'Котэ не одобряет?',
    name: 'Нямушка',
    taste: 'с рыбой',
    portion: '40 порций',
    present: '2 мыши в подарок',
    additional: '',
    weight: '2',
    units: 'кг',
    description_selected: 'Головы щучьи с чесноком да свежайшая сёмгушка.',
  },
  {
    title_default: 'Сказочное заморское яство',
    title_selected_hovered: 'Котэ не одобряет?',
    name: 'Нямушка',
    taste: 'с курой',
    portion: '100 порций',
    present: '5 мышей в подарок',
    additional: 'заказчик доволен',
    weight: '5',
    units: 'кг',
    description_selected: 'Филе из цыплят с трюфелями в бульоне.',
  },
];
